packageId: hl7.fhir.us.health-care-surveys-reporting
canonical: http://hl7.org/fhir/us/health-care-surveys-reporting
fhirVersion: 4.0.1
parameters:
  show-inherited-invariants: false
  path-expansion-params: "../../input/Parameters-expansion-parameters-health-care.json"
  pin-canonicals: pin-all
  auto-oid-root: 2.16.840.1.113883.4.642.40.59
applyExtensionMetadataToRoot: false
id: hl7.fhir.us.health-care-surveys-reporting
name: HealthcareSurveysReporting
title: Health Care Surveys Reporting
copyrightYear: 2025+
releaseLabel: STU 2
description: "This implementation guide (IG) provides Health Level Seven (HL7 FHIR) resources to define standards. 
  This guide contains a library of FHIR profiles and is compliant with FHIR Release 4."
publisher:
  name: HL7 International / Public Health
  url: http://www.hl7.org/Special/committees/pher
  email: ord@lists.HL7.org
extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: pher
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: 3
jurisdiction: urn:iso:std:iso:3166#US
status: active
version: 2.0.0
dependencies:
  hl7.fhir.us.core:
    version: 6.1.0
    uri: http://hl7.org/fhir/us/core/ImplementationGuide/hl7.fhir.us.core#6.1.0
    id: hl7fhiruscore
  hl7.fhir.us.ph-library:
    version: 1.0.0
    uri: http://hl7.org/fhir/us/ph-library/ImplementationGuide/hl7.fhir.us.ph-library#1.0.0
    id: hl7fhirusphlibrary
  hl7.fhir.uv.smart-app-launch:
    version: 2.2.0
    uri: http://hl7.org/fhir/smart-app-launch/ImplementationGuide/hl7.fhir.uv.smart-app-launch
    id: smartapplaunch
  hl7.fhir.uv.subscriptions-backport.r4:
    version: 1.1.0
    uri: http://hl7.org/fhir/uv/subscriptions-backport/ImplementationGuide/hl7.fhir.uv.subscriptions-backport
    id: subscriptionsIg
  hl7.fhir.uv.sdc: 
    version: 3.0.0
    uri: http://hl7.org/fhir/uv/sdc/ImplementationGuide/hl7.fhir.uv.sdc#3.0.0
    id: sdcIg